# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=140, verbose_name='Nome da categoria')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='T\xedtulo')),
                ('text', models.CharField(max_length=1000, verbose_name='Texto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.CategoryNews', verbose_name='Categoria')),
            ],
        ),
    ]
