# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorynews',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': '01. Categorias'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Not\xedcia', 'verbose_name_plural': '02. Not\xedcias'},
        ),
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_cateogory', to='news.CategoryNews', verbose_name='Categoria'),
        ),
    ]
